### ISSUE TITLE
No by-host stats at all

### ISSUE THREAD

**Issue by andrewelkin** [oofnikj/iptmon#18]
Hi!
thank you for the plugin, but I'm afraid I could not get what I needed. After install it's all nice but there were no firewall based stats. I assume they are needed for per-host graph presented in readme.
I went to Collectd Settings; the Firewall plugin was disabled. I enabled it but I had to change "Instance name" for both iptable preset rules (NO spaces allowed there, they were red-ed).
Enabled Firewall plugin, reboot, nothing changed. No per-host stats, probably it's expected to be a "Firewall" tab in the Statistics, but I got there only "Processor, Interfaces, Wireless, System load, Memory".  
Where did I get it wrong?
OpenWrt 21.02 luci git-21.295.67054-13df80d

**Comment by mstojek** [comment]
First you may want to login to the shell and execute command:
`iptables -t mangle -L`
Take a look if you have any iptmon entries (probably not since you see no stats). If table is empty execute another command:
`iptmon init`
This time you should see adding some static hosts to the mangle table (if you have static hosts defined).
Take a look at the issue: [#15](https://github.com/oofnikj/iptmon/issues/15) and apply workarounds that they suggest there.

**Comment by andrewelkin** [comment]
Thank you, it works now!
